apiVersion: v1
kind: PersistentVolume
metadata:
 name: elasticsearch-pv-storage
 namespace: elasticsearch
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 10Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: elasticsearch-pv-claim
 namespace: elasticsearch
spec:
 storageClassName: standard
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 10Gi
---